backend:
  # name: git-gateway
  name: test-repo
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "stories"
    editor:
      preview: false
    label: "Stories"
    folder: "src/pages/stories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "story-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Publish Date", name: "date", widget: "datetime", hint: This is how you can order the stories on the website.}
      - {label: Story Gallery, name: gallery, widget: object, fields: [
          {label: Images, name: images, widget: list, fields: [
            {label: Image, name: image, widget: image}, 
            {label: Title, name: title, widget: string}, 
            {label: Model, name: model, widget: string},
          ]}
        ]}

  - name: "pages"
    editor:
      preview: false
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Home, name: heroSwiper, widget: object, fields: [
              {label: Title, name: title, widget: string},
              {label: Subtitle, name: subtitle, widget: string},
              {label: Slide Show, name: images, widget: list, fields: [
                {label: Image, name: image, widget: image}, 
                {label: Title, name: title, widget: string} 
              ], hint: "David, add 3 to 5 images maximum here, not more! So the website it loads fast in slow internet connections and it is free of performance issues."} 
            ]}
          - {label: Biography, name: biography, widget: object, fields: [
                {label: Bio, name: text, widget: text},
                {label: Author, name: author, widget: string},
                {label: Tagline, name: tagline, widget: string}
            ]}
          - {label: Contact, name: contact, widget: object, fields: [
                {label: Form Title, name: title, widget: string},
                {label: E-mail address, name: email, widget: string}
            ]}